apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pinniped-supervisor-cert
  namespace: pinniped-supervisor
  annotations:
    kapp.k14s.io/change-group: "pinniped-supervisor.tap.ullom.xyz/certificate"
spec:
  secretName: pinniped-supervisor-tls-cert
  dnsNames:
  - pinniped-supervisor.tap2.ullom.xyz
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
