apiVersion: idp.supervisor.pinniped.dev/v1alpha1
kind: OIDCIdentityProvider
metadata:
  namespace: pinniped-supervisor
  name: auth0
  annotations:
    kapp.k14s.io/change-group: "pinniped-supervisor.tap.ullom.xyz/oidc-idp"
    kapp.k14s.io/change-rule: "upsert after upserting pinniped-supervisor.tap.ullom.xyz/ingress"
spec:
  # Specify the upstream issuer URL.
  issuer: https://ullom.us.auth0.com/

  # Specify how to form authorization requests to GitLab.
  authorizationConfig:
    additionalScopes: ["openid", "email", "profile"]
    allowPasswordGrant: false

  # Specify how claims are mapped to Kubernetes identities.
  claims:
    username: email
    groups: "https://user-info.ullom.xyz/roles"

  # Specify the name of the Kubernetes Secret that contains your
  # application's client credentials (created below).
  client:
    secretName: auth0-client-credentials

---
apiVersion: v1
kind: Secret
metadata:
  namespace: pinniped-supervisor
  name: auth0-client-credentials
  annotations:
    kapp.k14s.io/change-group: "pinniped-supervisor.tap.ullom.xyz/oidc-idp"
    kapp.k14s.io/change-rule: "upsert after upserting pinniped-supervisor.tap.ullom.xyz/ingress"
type: secrets.pinniped.dev/oidc-client
stringData:
  clientID: ${AUTH0_CLIENT_ID}
  clientSecret: ${AUTH0_CLIENT_SECRET}

---
apiVersion: config.supervisor.pinniped.dev/v1alpha1
kind: FederationDomain
metadata:
  name: pinniped-supervisor-federation-domain
  namespace: pinniped-supervisor
  annotations:
    kapp.k14s.io/change-group: "pinniped-supervisor.tap.ullom.xyz/oidc-idp"
    kapp.k14s.io/change-rule: "upsert after upserting pinniped-supervisor.tap.ullom.xyz/ingress"
spec:
  issuer: https://pinniped-supervisor.tap2.ullom.xyz
  tls:
    secretName: pinniped-supervisor-tls-cert
