profile: build
ceip_policy_disclosed: TRUE # Installation fails if this is not set to true. Not a string.

shared:
  ingress_domain: tap2.ullom.xyz
  image_registry:
    project_path: "acrtapdemo.azurecr.io/tap-demo" # To be used by Build Service by appending "/buildservice" and used by Supply chain by appending "/workloads".
    username: "${AZURE_SP_CLIENT_ID}"
    password: "${AZURE_SP_CLIENT_SECRET}"

# buildservice: # Optional if the corresponding shared keys are provided.
#   kp_default_repository: "KP-DEFAULT-REPO"
#   kp_default_repository_username: "KP-DEFAULT-REPO-USERNAME"
#   kp_default_repository_password: "KP-DEFAULT-REPO-PASSWORD"

supply_chain: testing_scanning
ootb_supply_chain_testing_scanning: # Optional if the corresponding shared keys are provided.
  registry:
    server: "${INSTALL_REGISTRY_HOSTNAME}"
    repository: "tap-demo"
  # gitops:
  #   ssh_secret: "SSH-SECRET-KEY" # (Optional) Defaults to "".
grype:
  namespace: "dev" # (Optional) Defaults to default namespace.
  targetImagePullSecret: "tap-registry"
  metadataStore:
    url: https://metadata-store.tap2.ullom.xyz
    caSecret:
        name: store-ca-cert
        importFromNamespace: metadata-store-secrets
    authSecret:
        name: store-auth-token
        importFromNamespace: metadata-store-secrets
scanning:
  metadataStore:
    url: "" # Configuration is moved, so set this string to empty.