profile: view
ceip_policy_disclosed: TRUE # Installation fails if this is not set to true. Not a string.

shared:
  ingress_domain: tap2.ullom.xyz

contour:
  envoy:
    service:
      type: LoadBalancer # NodePort can be used if your Kubernetes cluster doesn't support LoadBalancing.

tap_gui:
  service_type: ClusterIP
  app_config:
    app:
      baseUrl: https://tap-gui.tap2.ullom.xyz
    catalog:
      locations:
        - type: url
          target: https://github.com/aullom1/tap-demo/blob/main/catalog/catalog-info.yaml
    backend:
      baseUrl: https://tap-gui.tap2.ullom.xyz
      cors:
        origin: https://tap-gui.tap2.ullom.xyz
    # kubernetes:
    #   serviceLocatorMethod:
    #     type: 'multiTenant'
    #   clusterLocatorMethods:
    #     - type: 'config'
    #       clusters:
    #         - url: CLUSTER-URL
    #           name: CLUSTER-NAME # Build profile cluster can go here.
    #           authProvider: serviceAccount
    #           serviceAccountToken: CLUSTER-TOKEN
    #           skipTLSVerify: TRUE-OR-FALSE-VALUE
    #         - url: CLUSTER-URL
    #           name: CLUSTER-NAME # Run profile cluster can go here.
    #           authProvider: serviceAccount
    #           serviceAccountToken: CLUSTER-TOKEN
    #           skipTLSVerify: TRUE-OR-FALSE-VALUE

appliveview:
  ingressEnabled: true
  sslDisabled: FALSE
