name: Setup Auth

on:
  workflow_dispatch

env:
  AZURE_SP_CLIENT_ID: ${{ secrets.AZURE_SP_CLIENT_ID }}
  AZURE_SP_CLIENT_SECRET: ${{ secrets.AZURE_SP_CLIENT_SECRET }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_ACCESS_KEY: ${{ secrets.AZURE_STORAGE_ACCOUNT_ACCESS_KEY }}

jobs:
  ConfigurePinnipedSupervisor:
    name: Configure pinniped-supervisor
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install Carvel tools
        run: ./auth/install-carvel.sh

      - name: Add pinniped-supervisor
        run: ./auth/pinniped-supervisor/install.sh
      
      - name: Add pinniped-concierge
        run: ./auth/pinniped-concierge/install.sh
