# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch

env:
  AZURE_SP_CLIENT_ID: ${{ secrets.AZURE_SP_CLIENT_ID }}
  AZURE_SP_CLIENT_SECRET: ${{ secrets.AZURE_SP_CLIENT_SECRET }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      # - name: Run a one-line script
      #   run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Install pivnet cli
        run: |
          wget -O pivnet https://github.com/pivotal-cf/pivnet-cli/releases/download/v3.0.1/pivnet-linux-amd64-3.0.1
          chmod +x pivnet
          sudo mv pivnet /usr/local/bin
          pivnet version
      
      - name: Azure login
        run: az login --service-principal -u $AZURE_SP_CLIENT_ID -p $AZURE_SP_CLIENT_SECRET --tenant $AZURE_TENANT_ID

      - name: Install tanzu cli
        run: |
          $PIVNET_API_TOKEN=$(az keyvault secret show -n pivnet-api-token --vault-name kv-tanzu | jq -r .value)
          pivnet login --api-token $PIVNET_API_TOKEN
          pivnet download-product-files --product-slug='tanzu-application-platform' --release-version='1.3.0' --product-file-id=1310085
          mkdir $HOME/tanzu
          tar -xvf tanzu-framework-linux-amd64.tar -C $HOME/tanzu
          export TANZU_CLI_NO_INIT=true
          cd $HOME/tanzu
          export VERSION=v0.25.0
          sudo install cli/core/$VERSION/tanzu-core-linux_amd64 /usr/local/bin/tanzu
          tanzu version
          tanzu plugin install --local cli all
          tanzu plugin list --local cli all
      
